#!/bin/sh -e
# This script can be called in the following ways:
# Claudio A. Silva <claudiosilva@duzeru.org>
# After the package was installed:
#       <postinst> configure <old-version>
#
# Este Script vai pre-configurar o pacote
# If prerm fails during upgrade or fails on failed upgrade:
#       <old-postinst> abort-upgrade <new-version>
#
# If prerm fails during deconfiguration of a package:
#       <postinst> abort-deconfigure in-favour <new-package> <version>
#                  removing <old-package> <version>
#
# If prerm fails during replacement due to conflict:
#       <postinst> abort-remove in-favour <new-package> <version>


case "$1" in
    configure)
     
      plymouth-set-default-theme duzeru-logo
           
	if which update-initramfs >/dev/null 2>&1
	then
	    update-initramfs -u
	fi
	
	;;

    abort-upgrade|abort-deconfigure|abort-remove)
	;;

    *)
	echo "$0 called with unknown argument \`$1'" 1>&2
	exit 1
	;;
esac


exit 0
